# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2b4cbf9932f014e0080aee66591c12ff7a271d9e4d1c012dc21b37135854e969ecd2f74d4e79437df6e6756eef28edc1f5bafde8570cdc2bd493c446e602b65

test:
  secret_key_base: 377fd97935456169ed13ef36d7cc97263784858e02feeec915771f7fdef5b39fdc06ae8c58a9576aeb82e0c00206dbc25d30831c7a85a7729fb8b3f354004560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
